#!/usr/bin/env bash

# check bucket name
if [ -z "$1" ]; then
   echo "There needs to be a bucket name eg ./bucket my-bucket-name"
   exit 1
fi

aws s3api create-bucket --bucket $1 --region ap-southeast-2 --create-bucket-configuration  LocationConstraint=ap-southeast-2